### ISSUE TITLE
Base setup not working: cannot get /

### ISSUE THREAD

**Issue by shaula** [webapplate/webapplate#103]
Hello,
I just tried checking out the master of the current repository, but the server.js reports a 404 "Cannot GET /" no matter what resource I try to request.

I issued the following commands:
```
$ git clone https://github.com/webapplate/webapplate.git webapplate
$ cd webapplate
$ npm install -g grunt-cli bower karma
$ npm install
$ node server.js
```
I've not changed any code or config file in this case. What did I wrong in order to get it running? My problem is: my existing webapplate application does not work since I merged changes from the trunk.

**Comment by gasolin** [comment]
fixed, thanks for fire the bug. The issue is cause by express change there implementation of `express.static` API, which cause all static files can be hosted properly. 

Please try it again.

**Comment by shaula** [comment]
Thanks for your fast response; master is working again :-)
