### ISSUE TITLE
Missing modules on ArchLinux node 0.12

### ISSUE THREAD

**Issue by asdofindia** [webapplate/webapplate#97]
Followed the readme, cloned git, npm install'd.
```
$ grunt
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module 'lodash/lang/isFunction'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'hooker'
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "jscs.js" tasks...ERROR
>> Error: Cannot find module 'vow-fs'
Loading "mochacov.js" tasks...ERROR
>> Error: Cannot find module 'mkdirp'
Loading "myth.js" tasks...ERROR
>> Error: Cannot find module 'autoprefixer-core'
Loading "zip.js" tasks...ERROR
>> Error: Cannot find module 'jszip'
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'StringScanner'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

Tried running nvm, n, etc to run other versions of node. Version 0.10.36 also gives the same error as above. Am I missing some command?

**Comment by asdofindia** [comment]
I was having internet connection problems while installing for the first time. So this was probably caused due to some corrupted cache (although `npm cache clean` didn't work). 
Removing the node_modules folder and starting over, or npm install manually each package seems to be working.

**Comment by gasolin** [comment]
Thanks for finding that. I think it's a problem that webapplate needs some time to fetch required libraries.
